project:
  type: website
  output-dir: _site
  render:
    - index.qmd

profile:
  group:
    - [english, spanish]

website:
  favicon: images/logo.png

# Global configuration (no navbar here to avoid merging/duplication)

format:
  html:
    theme: cosmo
    css: styles.css
  revealjs:
    theme: [default, theme.scss]
    logo: images/logo.png
    footer: "kerasnip v0.1.0.900"
    center: false
