project:
  output-dir: _site/es

lang: es

website:
  title: "Presentaciones de kerasnip"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
    right:
      - text: "English"
        href: /index.html
