lang: es
project:
  output-dir: _site/es
format:
  revealjs:
    logo: ../../../images/logo.png
    css: ../../../styles.css
    menu:
      custom:
        - title: Language
          icon: <i class="fa fa-globe"></i>
          content: |
            <ul class="reveal-menu-custom">
              <hr>
              <li><a href="../index.html"><i class="fa fa-language"></i> English</a></li>
              <hr>
              <li><a href="index.html"><i class="fa fa-language"></i> <b>Español</b></a></li>
            </ul>
