lang: en
format:
  revealjs:
    logo: ../../images/logo.png
    css: ../../styles.css
    menu:
      custom:
        - title: Language
          icon: <i class="fa fa-globe"></i>
          content: |
            <ul class="reveal-menu-custom">
              <li><a href="index.html"><b>English</b></a></li>
              <li><a href="es/index.html">Español</a></li>
            </ul>
