project:
  type: website
  output-dir: _site

profile:
  group:
    - [english, spanish]

website:
  favicon: ../../images/logo.png

format:
  revealjs:
    theme: [default, ../../theme.scss]
    center: false
