lang: en
header-includes:
  - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

website:
  favicon: ../../images/logo.png
format:
  revealjs:
    logo: ../../images/logo.png
    css: ../../styles.css
    menu:
      custom:
        - title: Language
          icon: <i class="fa fa-language"></i>
          content: |
            <ul class="reveal-menu-custom">
              <br>
              <li><a href="index.html"><b>English</b></a></li>
              <br>
              <li><a href="es/index.html">Español</a></li>
            </ul>
